package action.webrtc

import util.Program.Env
import util.{Helper, Program}

object Sync extends Helper {
  def run(platform: Platform): Program[Unit] = platform match {
    case Platform.IOS =>
      for {
        _ <- shell("mkdir", "-p", root.lib)

        _ <- file.exists(root.lib.depot_tools) match {
          case true => for {
            _ <- putEnv(Env(root.lib.depot_tools, Map()))
            _ <- echo("Update to the latest depot_tools")
            _ <- shell("git", "pull")
          } yield ()
          case false => for {
            _ <- putEnv(Env(root.lib, Map()))
            _ <- echo("Clone depot_tools")
            _ <- shell("git", "clone", "https://chromium.googlesource.com/chromium/tools/depot_tools.git")
          } yield ()
        }

        _ <- putEnv(Env(root.lib, Map("GYP_DEFINES" -> "OS=ios")))
        _ <- echo("Configure gclient for iOS build")
        _ <- shell("gclient", "config", "--unmanaged", "--name=src", "https://chromium.googlesource.com/external/webrtc")

        _ <- echo("Write `target_os` in `.gclient` generated by `gclient config`")
        _ <- file.append(root.lib.`.gclient`, "target_os = ['ios', 'mac']")

        _ <- echo("Sync WebRTC to latest release branch")
        _ <- shell("gclient", "sync", "--with_branch_heads")
      } yield ()

    case Platform.Android => ???
  }
}
